[env]
framework = arduino
monitor_speed = 115200
lib_deps =
    GyverLibs/EncButton
    GyverLibs/GyverOLED


[env:nano328new]
platform = atmelavr
board = nanoatmega328new


[env:pcbusbasp]
platform = atmelavr
board = nanoatmega328new
upload_protocol = usbasp
upload_flags =
    -Pusb
    -B100

